actors:
  alice:
    image_url: /images/actors/alice.png
    name: alice
    url: http://sns.example.com/alice
  bob:
    image_url: /images/actors/bob.png
    name: bob
    url: http://sns.example.com/bob
  Yoshikai:
    image_url: /images/actors/bob.png
    name: Yoshikai
    url: https://twitter.com/yoshikai_
  Taiga:
    image_url: /images/actors/alice.png
    name: Taiga
  Shimizo:
      image_url: /images/actors/bob.png
      name: Shimizo

author: alice
description: FILMS和光のPodcast
description_long: 映画館のある和光市のソーシャルアパートメントの住人たちによるPodcast
email: info@example.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics: UA-106859358-2
hashtag: FILMS-WAKO
itunes_podcast_url:
keywords: comma,separated,keywords
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: FILMS-WAKO.fm
url: https://films-wako.netlify.com/
